---
- name: Destroy
  hosts: localhost
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  become: false
  tasks:
    # Developer must implement.
    - name: "Destroy server(s) for molecule scenario"
      ansible.builtin.include_role:
        name: molecule_vsphere
        tasks_from: destroy.yml

    # Mandatory configuration for Molecule to function.
    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      when: server.changed | default(false) | bool
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
      delegate_to: localhost
