---
dependency:
  name: galaxy
  options:
    force: true
    ignore-certs: false
    ignore-errors: false
    role-file: requirements.yml
    requirements-file: requirements.yml

platforms:
  - name: slm-cc-base-target-host
    groups:
      - target_host
    # Kubevirt
    image: quay.io/containerdisks/ubuntu:24.04
    volume_size: 20Gi
    instancetype: u1.large
    # Openstack
    image_name: Ubuntu 24.04 64-bit
    flavor: m1.large

  - name: slm-cc-base-consul-vault-prometheus-host
    groups:
      - consul_vault_prometheus_host
      - consul
      - vault
      - prometheus
      - prometheus-config
    # Kubevirt
    image: quay.io/containerdisks/ubuntu:24.04
    volume_size: 20Gi
    instancetype: u1.large
    # Openstack
    image_name: Ubuntu 24.04 64-bit
    flavor: m1.large

  # Old vsphere platform definition, kept for reference
  # - name: target-host
  #   template_name: ubuntu-22-04
  #   groups: ['ssh', 'target_host']
  # - name: consul-vault-prometheus-host
  #   template_name: ubuntu-22-04-docker
  #   groups: ['consul', 'vault', 'prometheus', 'prometheus-config']

ansible:
  cfg:
    defaults:
      host_key_checking: false
      verbosity: 1
    ssh_connection:
      pipelining: true
  env:
    # ANSIBLE-SPECIFIC:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"

    # SLM-SPECIFIC:
    SLM_HOSTNAME: myhost.local
    SLM_IP: 172.17.0.1
    SLM_VERSION: 1.5.0-SNAPSHOT
    INSTALL_DIRECTORY: /opt/eclipse-slm

    # ROLE-SPECIFIC:
    # RESOURCE_ID: 6e901402-a622-4957-ac79-41cece9141e8
    # RESOURCE_NAME: target_host
    VAULT_URL: http://vault:8200
    CONSUL_URL: http://consul:8500

  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --diff
        - --force-handlers
        - -e target_hosts="all:!consul:!vault:!prometheus"
      ansible_navigator:
        - --mode stdout
        - --pull-policy missing
        - --execution-environment-image ghcr.io/ansible/community-ansible-dev-tools:latest

  playbooks:
    create: ../default/create-kv.yml
    destroy: ../default/destroy-kv.yml
    prepare: prepare.yml
    converge: converge.yml
    cleanup: cleanup.yml
    verify: verify.yml

scenario:
  name: install
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
  destroy_sequence:
    - destroy
